### ISSUE TITLE
pip package support

### ISSUE THREAD

**Issue by Stonesjtu** [deehzee/unionfind#1]
Hi, thanks for your helpful codes at first. I'm wondering if you are interested in upload your code into a pip installable package. Maybe I can offer help on this.

**Comment by tommyjcarpenter** [comment]
I second this; I am currently repackaging your code in my code, because I can't pip it!

**Comment by hagai-helman** [comment]
[My fork](https://github.com/hagai-helman/unionfind) of this repository is now installable via pip:

```bash
pip install pyunionfind
```

```python
from unionfind import UnionFind
```

**Comment by deehzee** [comment]
Thanks @hagai-helman and sorry @Stonesjtu - I haven't been monitoring the repository and notifications. I am glad this has been packaged.

**Comment by deehzee** [comment]
Updated README with link to @hagai-helman's fork.
